const texts_en = {
    chooseLanguage: "Choose language",
    switchTheme: "Switch to light / dark version",
    openSidebar: "Open Sidebar",
    closeSidebar: "Kenar Çubuğunu Aç",
    expandCollapseSidebar: "Expand / Collapse Sidebar",
    close: "Close",
    pages: "Pages",
    dashboards: "Dashboards",
    main: "Main",
    customers: "Customers",
    bestCustomers: "Best Customers",
    activity: "Activity",
    notifications: "Notifications",
    yourProfile: "Your profile",
    administrator: "Administrator",
    settings: "Settings",
    signOut: "Sign Out",
    mainDashboard: "Main Dashboard",
    stampsOfThemonth: "Stamps of the month",
    totalGiven: "Total given",
    stamps: "Stamps",
    activeCustomers: "Active Customers",
    daily: "Daily",
    members: "Members",
    newCustomers: "New Customers",
    weekly: "Weekly",
    followers: "Followers",
    givenRewardsWeekly: "Given rewards (weekly)",
    coffee: "Coffee",
    cake: "Cake",
    meal: "Meal",
    childToy: "Child Toy",
    discount: "Discount",
    topRewards: "Top Rewards",
    rewardType: "Reward Type",
    totalCustomers: "Total Customers",
    totalStamps: "Total Stamps",
    rewardsCost: "Rewards Cost",
    totalProfit: "Total Profit",
    visits: "Visits",
    customersDashboard: "Customers Dashboard",
    name: "Name",
    email: "Email",
    spent: "Spent",
    lastStamp: "Last Stamp",
    originCountry: "Country",
    activityDashboard: "Activity Dashboard",
    recentActivity: "Recent Activity",
    today: "Today",
    yesterday: "Yesterday",
    stamped: "stamped",
    time: "time",
    inAvsallar: "in Avsallar",
    stampsVsRewards: "Stamps vs Rewards",
    rewards: "Rewards",
    sendNotification: "Send Notification",
    title: "Title",
    bodyOfTheMessage: "Body of the message",
    send: "Send",
    from: "From",
    with: "With"
};

export default texts_en;
