const texts_tr = {
    chooseLanguage: "Dil seçin",
    switchTheme: "Açık / koyu temaya geç",
    openSidebar: "Kenar Çubuğunu Aç",
    closeSidebar: "Kenar Çubuğunu Kapat",
    expandCollapseSidebar: "Kenar Çubuğunu Genişlet / Daralt",
    close: "Kapat",
    pages: "Sayfalar",
    dashboards: "Paneller",
    main: "Ana Sayfa",
    customers: "Müşteriler",
    bestCustomers: "En İyi Müşteriler",
    activity: "Aktivite",
    notifications: "Bildirimler",
    yourProfile: "Profiliniz",
    administrator: "Yönetici",
    settings: "Ayarlar",
    signOut: "Çıkış Yap",
    mainDashboard: "Ana Paneli",
    stampsOfThemonth: "Ayın Damgaları",
    totalGiven: "Toplam Verilen",
    stamps: "Damgalar",
    activeCustomers: "Aktif Müşteriler",
    daily: "Günlük",
    members: "Üyeler",
    newCustomers: "Yeni Müşteriler",
    weekly: "Haftalık",
    followers: "Takipçiler",
    givenRewardsWeekly: "Verilen ödüller (haftalık)",
    coffee: "Kahve",
    cake: "Pasta",
    meal: "Yemek",
    childToy: "Çocuk Oyuncağı",
    discount: "İndirim",
    topRewards: "En Popüler Ödüller",
    rewardType: "Ödül Türü",
    totalCustomers: "Toplam Müşteri",
    totalStamps: "Toplam Damga",
    rewardsCost: "Ödül Maliyeti",
    totalProfit: "Toplam Kar",
    visits: "Ziyaretler",
    customersDashboard: "Müşteri Paneli",
    name: "İsim",
    email: "E-posta",
    spent: "Harcanan",
    lastStamp: "Son Damga",
    originCountry: "Ülke",
    activityDashboard: "Aktivite Paneli",
    recentActivity: "Son Aktivite",
    today: "Bugün",
    yesterday: "Dün",
    stamped: "damgalandı",
    time: "kez",
    inAvsallar: "Avsallar'da",
    stampsVsRewards: "Damgalar vs Ödüller",
    rewards: "Ödüller",
    sendNotification: "Bildirim Gönder",
    title: "Başlık",
    bodyOfTheMessage: "Mesajın içeriği",
    send: "Gönder",
    from: "İtibariyle",
    with: "İle"
};

export default texts_tr;
